name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Elixir CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: ["1.17"]
        otp: ["26"]

    env:
      MIX_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir and OTP
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: deps-${{ runner.os }}-

      - name: Install dependencies
        run: mix deps.get

      - name: Create PLT directory
        run: mkdir -p priv/plts

      - name: Cache PLT files
        uses: actions/cache@v3
        with:
          path: priv/plts
          key: plt-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: plt-${{ runner.os }}-

      - name: Run Credo
        run: mix credo --strict

      - name: Build PLT
        run: mix dialyzer --plt --plt-core-path priv/plts --plt-local-path priv/plts --no-check --quiet

      - name: Run Dialyzer
        run: mix dialyzer

      - name: Run Tests
        run: mix test

